### ISSUE TITLE
Filtering by Tags allows no selection

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#25]
Basically if you accidentally hit apply instead of the toggle button you, it will return no results because no tags are checked.

**Comment by puregallery** [comment]
I'm a little confused...what do you mean by 'hit apply'? 
Once you return from the 'Edit Tags' screen, I do reset the selections automatically though.

**Comment by Nostang3** [comment]
So you go into Albums, click on the filter icon and it will bring up the dialog where you can choose tags, location, or media type. If you select the tags section it will bring up the list of tags and the ANY/ALL toggle at the bottom. If you do nothing but hit apply at this point, because you meant to toggle and missed, it will filter everything and say no media to display here. I was just suggesting that that there should be some check in place that prevents you from filtering without a tag selected.

**Comment by puregallery** [comment]
Ah, got it...thanks.

**Comment by Nostang3** [comment]
PG no longer allows empty tag filters. Prompts user with a toast letting them know they need to apply a tag. 

This works but I wonder if you think it would be better to disable the apply button until a tag is selected? Or that tag dialog doesn't get dismissed if no tag is selected when you do hit apply?

**Comment by Nostang3** [comment]
@puregallery I forgot, what was changed here? The tag dialog doesn't get dismissed when I try to apply with no tags and a toast appears. It seems this is what I mentioned in my previous comment. I just wanted to double check what I should be testing. 

Also, I feel I should mention that I was a software tester in a previous job, and I'm very good at finding bugs. I just don't want you to think I'm harping on your app by submitting all these issues.

**Comment by puregallery** [comment]
Yes, we didn't want the dialog to be dismissed when no option is selected.
Don't worry man, you are helping me a lot through this testing and am grateful for that :) Don't think otherwise.
I released another app a while back and I didn't have any testers contributing for that, and you should've seen the ratings section. For every bug that the users have found, I got a one star review and they never got removed even after fixing the bugs. I has been such a pain and I realized that its better to remove all the possibilities before making the app go live in production.
