### ISSUE TITLE
Nested Album/TAG View in home screen

### ISSUE THREAD

**Issue by puregallery** [puregallery/Pure-Gallery-Support#29]

**Comment by Nostang3** [comment]
Is this view, specifically meant so you can scroll through the individual photos and see the tag icon on them?

**Comment by puregallery** [comment]
This is just to give users a quick access to their albums without having to dive into them individually. As you can see, you can't really 'manage' your media this way. Btw, I need to give an option to manage/view the album's properties...still not sure where to include that.
Anyway, this is similar to the play store's UI and has been on my list for a long time. Just wanted to remove this off my list. 
Do you know any other view that would look good for gallery? I saw some apps have a list view with a parallax effect on the cover image as the list scrolls. It is easy to implement...but am not a big fan of that. Looking for ideas :)

**Comment by Nostang3** [comment]
By album properties you mean like Size and Path to folder? You could attach the option to a long press to the album with a floating bar at the bottom for say delete and details. Could also change the top bar options based on album selection. 

Also, speaking of top bar have you thought about moving the share and delete options down to the floating bar to clean up the top bar? I feel the bottom bar needs more options and you're not splitting up your options from having some at the top and some at the bottom.

The parallax effect is on the only other one I can think of. You could probably make more views based on off mixing styles. Like make the cards you have now into maybe parallax cards. Have just the parallax view where the card takes up the width, then maybe have cards with some spacing around them instead of them touching.

**Comment by puregallery** [comment]
Yeah, you can see the album options in the grid view when you click on the three dot icon on the bottom of every album. I'm thinking of adding that next to the album title for nested albums.

When in selection mode, we should not do any modifications to the displayed list...so, we need to hide the 'filter' and 'sort' options on the top bar. Moving share and delete to the bottom bar will end up making the top bar empty without any icons...and I guess that'd be fine.Btw, I need to add 'copy' function to the app as well...so, that's another option coming soon...'select all' would be another one.

I'll play around with the parallax cards. I want a unique theme/view to the home page frankly...need to check out some sample mocks on uplabs I guess
