### ISSUE TITLE
Scrolling in album is sometimes not smooth

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#66]
In my folder of 1400 files, at the bottom(where I notice it), it does not scroll smoothly. It's not until I scroll up a ways before it starts to smooth out. I did some more scrolling and the issue is not directly related to the bottom, it comes and goes as I work my way up the album.

**Comment by puregallery** [comment]
How many columns did you have?
What is the typical file size of the items in that folder?

**Comment by Nostang3** [comment]
This particular album is 4 columns sorted and grouped by date. The average photo is probably around ~100k but there can be photos higher in the hundreds and some that may be a few megabytes.

**Comment by puregallery** [comment]
Are we talking about the scrollbar not moving smoothly or the app itself lags?

**Comment by Nostang3** [comment]
No, the actual pictures. They will scroll smoothly, then suddenly start skipping, then as you keep going will go back to scrolling smoothly. It may be the app itself lagging behind causing the issue but you notice it through the pictures.

**Comment by puregallery** [comment]
Yeah...this is the reason many apps refrain from providing high column values...Google photos has all its rendering done at a native(C++) level and that's why their performance is great even with 8 columns.
Images in general take up a lot of memory in Android. When the column count increases, I can reduce the quality(dimensions) of thumbnails...but that will clear the cache for older dimension thumbnails and the app will have to cache the thumbnails from beginning...meaning, there will be a slight delay in loading images for every column change. Do you think this will be acceptable to users?

Btw, in the next release I'm including a feature to allow high quality thumbnail setting which will help users who want to use big thumbnails...mostly targeting users who would prefer less columns. 
I need to look into reducing the thumbnail quality for high column count.

**Comment by Nostang3** [comment]
I think column changes would be a set it and forget it thing. I leave my big folder at 4 so I can see more pictures as I scroll because I have so many. I never change it. So a slight delay if I did change it wouldn't really bother me. I'd imagine other people would feel the same way.

Low quality thumbnails don't really bother me as long as I can clearly see what's going on in the photo.

**Comment by puregallery** [comment]
Shall we clean up the bugs...We are now at RC4 and I need help with the bugs in RC2 and RC3 milestones

**Comment by Nostang3** [comment]
Scrolling in an album is now consistent. Scrolling is now smooth and doesn't stutter like it did before. 

Edit: I've closed all the finished one I could in the RC2 and RC3 milestones. Some need to be updated to RC4 when you release it.
