### ISSUE TITLE
App Load Issues

### ISSUE THREAD

**Issue by Nostang3** [puregallery/Pure-Gallery-Support#97]
When opening the app, there will be a white screen that appears, then disappears,the home screen is then visible, then white screen reappears then fade down towards the navigation bar and the albums finally appear. This happens every time a new instance of PG is opened.

**Comment by puregallery** [comment]
Some of this is intended...to speed up the app load time, I had to introduce an intermediate splash screen.
Applying a theme to the splash screen is also going to slow down the process a bit...that's why it does not follow any theme options that you have set.

That being said, I am seeing some unexpected animations getting in the way...I will be pushing a fix today to address the animation issues.

**Comment by puregallery** [comment]
How do you feel about displaying a splash screen for about a second when the app launches? This is to finish up some initialization needed for the app...computing tags, locations, favorites etc. The time will vary based on the size of the library on the device...and is typically below a second in most cases.

In my testing, showing the splash screen until init is done made the app feel quite smooth at first launch...with the least amount of dropped frames I've seen till now.

P.S - your thoughts on the new icon?

**Comment by Nostang3** [comment]
I see nothing wrong with it. A lot of the popular apps do it: Twitter, Plex, and Snapchat. 

I like it. It's unique.
